### PR TITLE
Issue 58/azure serverless integrations

### PR DESCRIPTION
**Pull request by erichydrick**
#53 
I mistyped the issue number in the commit message, my bad

### CODE REVIEW

**Comment by erichydrick** [comment]
@dboulet01 It looks like merges from external forks don't work if the other developer doesn't have Azure CLI installed.

**Comment by erichydrick** [comment]
@dboulet01 It looks like this change broke the Terraform, but I can't see where I changed anything Terraform-

**Comment by dboulet01** [comment]
> @dboulet01 It looks like merges from external forks don't work if the other developer doesn't have Azure CLI installed.

the pipeline can't access repo secrets from a fork PR. if you clone, new branch, PR it'll run

**Comment by erichydrick** [comment]
Closing so I can do this from a branch rather than a fork.

**Comment by erichydrick** [comment]
FYI, I get a 403 when I try to push to a new branch on the main repo.

**Comment by dboulet01** [comment]
> FYI, I get a 403 when I try to push to a new branch on the main repo.

Can you try now? Thanks

**Pull request closed without merging**
