### PR TITLE
Add testing and linting

### PR DESCRIPTION
**Pull request by ricky-sb**
Adding test and lint functions

### CODE REVIEW

**Comment by ricky-sb** [comment]
In the GitHub actions,  can we run `yarn lint` and `yarn test`, and somehow make them show up in these "checks" section? I know it's possible with CircleCI somehow:

image

@dboulet01

**Comment by ricky-sb** [comment]
Looks like there's a tool for it here:  

https://github.com/marketplace/actions/lint-action

**Comment by dboulet01** [comment]
> In the GitHub actions, can we run `yarn lint` and `yarn test`, and somehow make them show up in these "checks" section? I know it's possible with CircleCI somehow:
> 
> image
> 
> @dboulet01

where would these commands fit in the existing pipeline? before or after build? will look into results showing up in PR

**Comment by ricky-sb** [comment]
>where would these commands fit in the existing pipeline? before or after build? will look into results showing up in PR  

Before the build. In order, it would be:  

1. Run linting (`yarn lint`)
2. Run tests (`yarn test`)
3. Run build (`yarn generate`)  


CodeClimate runs automatically, so don't worry about setting that up.

**Pull request merged**
