### PR TITLE
Build out FE footer

### PR DESCRIPTION
**Pull request by vai0**
## Summary
Builds out the footer and inserts it into the layout.
Feel free to nitpick this, went scss heavy rather than with tailwind here.

Partially addresses ticket https://accessamerica.atlassian.net/browse/CC-76

### CODE REVIEW

**Comment by ricky-sb** [comment]
Deployment failed because there's no SCSS compiler configured 
image

**Comment by vai0** [comment]
ahh, should i go about adding one or should I just convert the scss to css and tailwind? noticed awhile back you pulled out scss because it made HMR slow.

**Comment by ricky-sb** [comment]
Ah yeah that's right. Either works, you can compile it to CSS and just use
the generated output, or you could convert to Tailwind

**Comment by vai0** [comment]
hm, do you know how i can replicate this build error locally? `yarn build` runs without errors

**Comment by ricky-sb** [comment]
Looks like you fixed it 🤷‍♂️, I'll merge this in :)

**Pull request merged**
